- name: Create production server
  hosts: localhost
  connection: local
  vars:
    terraform_rc_path: .terraformrc
    terraform_path: ./tf
  tasks:
    - name: Prepare TF (set yandex mirror)
      copy:
        src: "{{ terraform_rc_path }}"
        dest: ~/.terraformrc

    - name: Run terraform
      environment:
        OS_AUTH_URL: "{{ lookup('env', 'OS_AUTH_URL') }}"
        OS_PROJECT_ID: "{{ lookup('env', 'OS_PROJECT_ID') }}"
        OS_PROJECT_NAME: "{{ lookup('env', 'OS_PROJECT_NAME') }}"
        OS_USER_DOMAIN_NAME: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') }}"
        OS_PROJECT_DOMAIN_ID: "{{ lookup('env', 'OS_PROJECT_DOMAIN_ID') }}"
        OS_USERNAME: "{{ lookup('env', 'OS_USERNAME') }}"
        OS_PASSWORD: "{{ lookup('env', 'OS_PASSWORD') }}"
        OS_REGION_NAME: "{{ lookup('env', 'OS_REGION_NAME') }}"
        OS_INTERFACE: "{{ lookup('env', 'OS_INTERFACE') }}"
        OS_IDENTITY_API_VERSION: "{{ lookup('env', 'OS_IDENTITY_API_VERSION') }}"
      terraform:
        project_path: "{{ terraform_path }}"
        force_init: yes
        state: present
      register: trfrm

    - name: Export server IP up
      lineinfile:
        path: ~/myenv
        regexp: '^DEPLOYMENT_SERVER_IP='
        line: "DEPLOYMENT_SERVER_IP={{ trfrm.outputs.servers.value.serverip }}"
        mode: '0644'
        create: yes

    - name: Add instance host (Ansible term)
      add_host:
        name: mhq-server
        groups: nodes
        ansible_host: "{{ trfrm.outputs.servers.value.serverip }}"
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Wait for instance creating
  hosts: localhost
  connection: local     
  
  tasks:
    - name: Wait for a ssh port become available
      wait_for:
        host: "{{ trfrm.outputs.servers.value.serverip }}"
        port: 22

- name: Start production database 
  hosts: mhq-server
  become: yes
  vars:
    sql_path: create.sql
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install postgresql server
      apt:
        name: postgresql
        state: present


    - name: Start postgresql service
      service:
        name: postgresql
        state: restarted
        enabled: yes

    - name: Set user password
      community.postgresql.postgresql_user:
        name: postgres
        password: 424242

    - name: Create database
      community.postgresql.postgresql_db:
        name: tasks

    - name: Copy sql import script
      copy:
        src: "{{ sql_path  }}"
        dest: /home/ubuntu/create.sql

    - name: Create tables
      community.postgresql.postgresql_script:
        db: tasks
        state: import
        target: /home/ubuntu/create.sql

- name: Prepare production for deploy
  hosts: mhq-server
  vars:
    service_path: botserver.service
    terraform_path: tf
  tasks:
    - block:
      - name: Install JDK
        apt:
          update_cache: yes
          name: openjdk-21-jdk-headless
          state: present
        become: yes

      - name: Create bot app service
        copy:
          src: "{{ service_path }}"
          dest: /etc/systemd/system/botserver.service
          mode: '0777'
        become: yes
    
      - name: Reload services
        systemd:
          daemon_reload: true
          name: botserver
          state: stopped
        become: yes
   
      rescue:
       - name: Clean up resources in case of error
         terraform:
           project_path: "{{ terraform_path }}"
           state: absent
         delegate_to: localhost