apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: opaque
stringData:
  db-username: {{ .Values.db.username | quote }} #postgres
  db-password: {{ .Values.db.password | quote }} #424242
